### ISSUE TITLE
Can't use string as an ARRAY ref while "strict refs" in use at ../tools/DelGet/DelGet.pl line 1043.

### ISSUE THREAD

**Issue by TobyBaril** [4ureliek/DelGet#2]
Hi,

I am trying to run the DelGet.pl script for a trio of Danaus species. I generated a nwk tree with fasttree, and edited this as it was not working with the script. However, I am still getting the following error when trying to run the script:

```
$ perl ../tools/DelGet/DelGet.pl monarchcon.txt
Can't use string ("danausMelanippus") as an ARRAY ref while "strict refs" in use at ../tools/DelGet/DelGet.pl line 1043.
```

My config file is here: [monarchcon.txt](https://github.com/4ureliek/DelGet/files/7553999/monarchcon.txt)

The original tree that didn't work (from fasttree):```(danausChrysippus:0.037341543,danausMelanippus:0.062983791,danausPlexippus:0.033347631);```

Thanks in advance for any help you can give me to get this up and running!

**Comment by 4ureliek** [comment]
Note: this discussion was moved to email, and was resolved.
